[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
via_ir = true
optimizer = true
optimizer_runs = 1000000
evm_version = "cancun"

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
hyperliquid = "${HYPERLIQUID_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options